#  vim:ts=4:sts=4:sw=4:et
#
#  Author: Hari Sekhon
#  Date: 2019-10-01 16:14:15 +0100 (Tue, 01 Oct 2019)
#
#  https://github.com/HariSekhon/Templates
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help improve or steer this or other code I publish
#
#  http://www.linkedin.com/in/harisekhon
#

ignored:
  # Maintainer is deprecated
  #- DL4000
  # FROM latest - dev images build on upstream latest tag intentionally
  - DL3007
  # apt-get install versions need not be pinned
  - DL3008
  # apk add versions need not be pinned
  - DL3018
  #- SC1010
  # - for dev images it's ok to use both curl and wget as they are dependencies of different scripts
  - DL4001

trustedRegistries:
  - docker.io
  #- my-company.com:5000
