#
#  Author: Hari Sekhon
#  Date: 2024-08-09 00:32:34 +0300 (Fri, 09 Aug 2024)
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https///github.com/HariSekhon/Templates
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help steer this or other code I publish
#
#  https://www.linkedin.com/in/HariSekhon
#

# ============================================================================ #
#                         P r e - C o m m i t   H o o k
# ============================================================================ #

---
#- id: trailing-whitespace
#  name: Trim Trailing Whitespace
#  description: This hook trims trailing whitespace.
#  entry: trailing-whitespace-fixer
#  language: python
#  types: [text]
