#
#  Author: Hari Sekhon
#  Date: [% DATE # 2025-04-07 21:03:21 +0800 (Mon, 07 Apr 2025) %]
#
#  [% VIM_TAGS %]
#
#  [% URL # https://github.com/HariSekhon/Templates %]
#
#  [% LICENSE %]
#
#  [% MESSAGE %]
#
#  [% LINKEDIN %]
#

---
disabled_rules: # rule identifiers to exclude from running
#  - colon
#  - comma
#  - control_statement
#  - file_length
#  - force_cast
#  - force_try
#  - function_body_length
#  - leading_whitespace
#  - line_length
#  - nesting
#  - operator_whitespace
#  - opening_brace
#  - return_arrow_whitespace
#  - statement_position
#  - todo
#  - trailing_newline
#  - trailing_semicolon
#  - trailing_whitespace
#  - type_body_length
#  - type_names
#  - valid_docs
#  - variable_name
#  - variable_name_min_length
#  - variable_name_max_length

included: # paths to include during linting. `--path` is ignored if present
  - MyApp
excluded: # paths to ignore during linting. Takes precedence over `included`
  - Carthage
  - Pods
  - fastlane
  - ${PWD}/MyApp/ThirdParty
  - ${PWD}/MyApp/SupportingObject/UIComponents
  - ${PWD}/MyApp/Screens/Signup/SignupViewController.swift
# parameterized rules can be customized from this configuration file
file_length:
  - 700
  - 1000
line_length:
  - 300
  - 350
# parameterized rules are first parameterized as a warning level, then error level
function_body_length:
  - 150 # warning
  - 200 # error
type_body_length:
  - 300 # warning
  - 400 # error
variable_name_max_length:
  - 30 # warning
  - 40 # error
variable_name_min_length:
  - 2 # warning
  - 1 # error
vertical_whitespace:
  - 2 # warning
  - 3 # error
trailing_whitespace:
  - 100 # warning
  - 300 # error
