#  vim:ts=2:sts=2:sw=2:et
#
#  Author: Hari Sekhon
#  Date: 2020-09-17 18:18:38 +0100 (Thu, 17 Sep 2020)
#
#  https://github.com/harisekhon/templates
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback
#  to help improve or steer this or other code I publish
#
#  http://www.linkedin.com/in/harisekhon
#

# ============================================================================ #
#                               T r a v i s   C I
# ============================================================================ #

# https://docs.travis-ci.com/user/customizing-the-build/

---
version: ~> 1.0

# ==============================================================
# https://docs.travis-ci.com/user/languages/minimal-and-generic/
language: bash
os:
  - linux

# ======================================================
# https://docs.travis-ci.com/user/environment-variables/
env:
  - PYTHONUNBUFFERED=1

# ==============================================
# https://docs.travis-ci.com/user/notifications/
notifications:
  email: false

# =================================================================================
# https://docs.travis-ci.com/user/customizing-the-build/#building-specific-branches
# https://docs.travis-ci.com/user/conditional-builds-stages-jobs
#branches:
#  only:
#    - master

# ========================================
# https://docs.travis-ci.com/user/caching/

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

cache:
  #- npm
  - pip
  #- packages # R
  - directories:
      - $HOME/.cache
      - $HOME/.cpan
      - $HOME/.cpanm
      - $HOME/.gem
      #- $HOME/.m2
      #- $HOME/.ivy
      #- $HOME/.ivy2
      #- $HOME/.gradle
      #- $HOME/.sbt
      #- $HOME/.groovy
      #- $HOME/.rvm
      #- $HOME/go/pkg
      # bash-tools is not a submodule, but downloaded so ok to cache whole
      - bash-tools

# ==============================================
# https://docs.travis-ci.com/user/job-lifecycle/

# avoid package checksum mismatches when installing packages
before_install:
  - sudo rm -f "${TRAVIS_ROOT}/etc/apt/apt.conf.d/99-travis-apt-proxy"
  - sudo rm -rf "${TRAVIS_ROOT}/var/lib/apt/lists/"*

install:
  - travis_retry make bash-tools

script:
  - travis_retry make test
