#
#  Author: Hari Sekhon
#  Date: [% DATE # 2020-09-23 19:04:15 +0100 (Wed, 23 Sep 2020) %]
#
#  [% URL %]
#
#  [% LICENSE %]
#
#  [% MESSAGE %]
#
#  [% LINKEDIN %]
#

# ============================================================================ #
#                         G C P   C l o u d   B u i l d
# ============================================================================ #

# References:
#
#     https://cloud.google.com/cloud-build/docs/build-config
#
#     https://cloud.google.com/cloud-build/docs/building/build-go
#
#     https://cloud.google.com/cloud-build/docs/access-private-github-repos


# XXX: See core cloudbuild.yml adjacent for more tips and tricks


# gcloud builds submit --config cloudbuild-golang.yaml .

# tars $PWD to bucket called ${PROJECT_ID}_cloudbuild

# $PROJECT_ID and $BUILD_ID are auto-populated by Cloud Build

---
timeout: 600s
steps:
  # uses the official 'golang' docker image from DockerHub to build the binary
  - name: golang
    args: ['go', 'build', '.']
    timeout: 500s
# uploads the given artifact paths to the GCS bucket along with a metadata file:
# artifacts-12345abc-6789-0d1e-23fa-4b5cd678e901.json
artifacts:
  objects:
    # XXX: you probably want a unique versioned directory path here to avoid overriding previous binaries
    #      or use Object Versioning - https://cloud.google.com/storage/docs/object-versioning
    location: 'gs://$PROJECT_ID-go/bin/$BUILD_ID/'
    # XXX: replace mybinary - should match the generated binary name (module basename in go.mod)
    paths: ['mybinary']
