#
#  Author: Hari Sekhon
#  Date: [% DATE # 2020-02-11 12:53:33 +0000 (Tue, 11 Feb 2020) %]
#
#  vim:ts=2:sts=2:sw=2:et
#
#  [% URL %]
#
#  [% LICENSE %]
#
#  [% MESSAGE %]
#
#  [% LINKEDIN %]
#

# ============================================================================ #
#                         G C P   C l o u d   B u i l d
# ============================================================================ #

# References:
#
#     https://cloud.google.com/cloud-build/docs/build-config
#
#     https://cloud.google.com/cloud-build/docs/build-debug-locally


# gcloud builds submit --config cloudbuild.yaml .
#
# cloud-build-local --config cloudbuild.yml --dryrun=false .

# tars $PWD to bucket called ${PROJECT_ID}_cloudbuild

---
timeout: 3660s

steps:
  - name: ubuntu:18.04
    entrypoint: bash
    args:
      - '-c'
      - |
        setup/ci_bootstrap.sh &&
        make build test
    timeout: 3600s
