#
#  Author: Hari Sekhon
#  Date: Wed Jan 5 16:53:05 2022 +0000
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/HariSekhon/Templates
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help steer this or other code I publish
#
#  https://www.linkedin.com/in/HariSekhon
#

# ============================================================================ #
#                              P r o m e t h e u s
# ============================================================================ #

---
global:
  scrape_interval: 15s # default: 1 minute
  evaluation_interval: 15s # evaluate rules every 15 sess (default: 1 minute)
  #scrape_timeout: 10s

#alerting:
#  alertmanagers:
#    - static_configs:
#        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
#rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # job_name adds label `job=<job_name>` to timeseries metrics
  - job_name: prometheus
    #metrics_path: /metrics
    #scheme: http
    #honor_timestamps: true
    #enable_compression: true
    #follow_redirects: true
    #enable_http2: true
    static_configs:
      - targets:
          - localhost:9090

  - job_name: demo
    static_configs:
      - targets:
          - demo.promlabs.com:10000
          - demo.promlabs.com:10001
          - demo.promlabs.com:10002
