%% #!/usr/bin/env mmdc -i -t dark -b transparent
%%
%%  Author: Hari Sekhon
%%  Date: [% DATE  #  2023-05-05 02:26:36 +0100 (Fri, 05 May 2023) %]
%%
%%  vim:ts=2:sts=2:sw=2:et
%%
%%  [% URL %]
%%
%%  [% LICENSE %]
%%
%%  [% MESSAGE %]
%%
%%  [% LINKEDIN %]
%%

%% ========================================================================== %%
%%                       M e r m a i d J S   D i a g r a m
%% ========================================================================== %%

%% See Sample diagrams in the Live Editor

%% https:%%mermaid.live/edit

%% choose type of diagram:
%%
%%   sequenceDiagram
%%   flowchart TD      # Flow Chart top down - 'graph' word seems to work too
%%   classDiagram
%%   stateDiagram-v2
%%   erDiagram         # Entity Relationship
%%   gantt
%%   journey           # User Journey
%%   gitGraph
%%   pie title My Title
%%   mindmap

%% Different syntax for each type of diagram :'-(
%%
%% Start Here:
%%
%%    https://mermaid.js.org/syntax/flowchart.html

%% ========================================================================== %%

%% directives can be on one line or multiline json (except it accepts single quotes as well as double quotes)

%% Themes and customizing themes:
%%
%%    https://mermaid.js.org/config/theming.html

%%{init: { 'logLevel': 'debug', 'theme': 'dark' } }%%

%% Git Graph examples:
%
%   see the Diagrams-as-Code repo's README.md source code at:
%
%     https://github.com/HariSekhon/Diagrams-as-Code/blob/master/README.md#github-flow-with-jira-ticket-integration


---
title: Node
---
flowchart LR
  id(content)
  Start --> Stop

### Some markdown
```mermaid
graph
   [....]
```

### Some more markdown
```mermaid
sequenceDiagram
   [....]
```

### Mermaid with custom title/desc
```mermaid
graph
   accTitle: My title here
   accDescr: My description here
   A-->B
```
