%% #!/usr/bin/env mmdc -i -t dark -b transparent
%%
%%  Author: Hari Sekhon
%%  Date: [% DATE  #  2023-05-05 02:26:36 +0100 (Fri, 05 May 2023) %]
%%
%%  vim:ts=2:sts=2:sw=2:et
%%
%%  [% URL %]
%%
%%  [% LICENSE %]
%%
%%  [% MESSAGE %]
%%
%%  [% LINKEDIN %]
%%

%% ========================================================================== %%
%%                       M e r m a i d J S   D i a g r a m
%% ========================================================================== %%

%% See Sample diagrams in the Live Editor

%% https:%%mermaid.live/edit

%% ========================================================================== %%

%% choose type of diagram:
%%
%%   sequenceDiagram
%%   flowchart TD      # Flow Chart top down - 'graph' word seems to work too
%%   classDiagram
%%   stateDiagram-v2
%%   erDiagram         # Entity Relationship
%%   gantt
%%   journey           # User Journey
%%   gitGraph
%%   pie title My Title
%%   mindmap

%% ========================================================================== %%

%%  Different syntax for each type of diagram :'-(
%%
%%  Start Here:
%%
%%      https://mermaid.js.org/syntax/flowchart.html

%% ========================================================================== %%

%% directives can be on one line or multiline json (except it accepts single quotes as well as double quotes)

%% Themes and customizing themes:
%%
%%    https://mermaid.js.org/config/theming.html

%%{init: { 'logLevel': 'debug', 'theme': 'dark' } }%%

%% ========================================================================== %%
%%                              Git Graph
%% ========================================================================== %%

%%  https://github.com/HariSekhon/Diagrams-as-Code/blob/master/README.md#github-flow-with-jira-ticket-integration

---
title: Node
---
flowchart LR
  id(content)
  Start --> Stop


%% ========================================================================== %%
%%                      MermaidJS in GitHub Markdown
%% ========================================================================== %%
%%
%%  https://github.com/HariSekhon/Diagrams-as-Code/blob/master/README.md#github-flow-with-jira-ticket-integration

### Some markdown
```mermaid
graph
   [....]
```

### Some more markdown
```mermaid
sequenceDiagram
   [....]
```

### Mermaid with custom title/desc
```mermaid
graph
   accTitle: My title here
   accDescr: My description here
   A-->B
```

%% ========================================================================== %%
%%                          Icon Cloud diagramas
%% ========================================================================== %%
%%
%%          https://text-to-diagram.com/?example=icons&b=mermaid

graph TD
  subgraph aws
    aws_db(<img src='https://icons.terrastruct.com/azure/Databases%20Service%20Color/Azure%20Database%20for%20PostgreSQL%20servers.svg' width='32' height='32' />)
    cache(<img src='https://icons.terrastruct.com/azure/_Companies/Azure%20Cache%20Redis%20Product%20icon.svg' width='32' height='32' />)
    ec2(<img src='https://icons.terrastruct.com/aws/_Group%20Icons/EC2-instance-container_light-bg.svg' width='32' height='32' />)

    ec2 <-->|get persisted data| aws_db
    ec2 <-->|get temporal data| cache
  end

  subgraph gcloud
    gcloud_db(<img src='https://icons.terrastruct.com/azure/Databases%20Service%20Color/Azure%20Database%20for%20PostgreSQL%20servers.svg' width='32' height='32' />)
  end

  aws_db -->|backup| gcloud_db

  dev(<img src='https://icons.terrastruct.com/essentials/005-programmer.svg' width='32' height='32' />)
  github(<img src='https://icons.terrastruct.com/dev/github.svg' width='32' height='32' />)

  dev -->|ssh| ec2
  dev -->|version control| github
