#
#  Author: Hari Sekhon
#  Date: Tue Feb 4 09:53:28 2020 +0000
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/harisekhon/templates
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback
#
#  https://www.linkedin.com/in/harisekhon
#


# ============================================================================ #
#                     T F s e c   G i t H u b   A c t i o n
# ============================================================================ #

# Comments on any PR that adds transgressions

name: tfsec-pr-commenter

on:
  pull_request:

jobs:
  tfsec:
    name: tfsec PR commenter
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@master

      - name: tfsec
        uses: tfsec/tfsec-pr-commenter-action@5e9f770638057da497182661aacbf640ca94f4e9
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
