#  vim:ts=2:sts=2:sw=2:et
#
#  Author: Hari Sekhon
#  Date: 2023-05-31 01:49:54 +0100 (Wed, 31 May 2023)
#
#  https://github.com/HariSekhon/Templates
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help steer this or other code I publish
#
#  https://www.linkedin.com/in/HariSekhon
#

# ============================================================================ #
#       U b u n t u   A u t o I n s t a l l e r   /   C l o u d - I n i t
# ============================================================================ #

---
name: Ubuntu AutoInstaller Cloud-Init

on:
  push:
    branches:
      - master
      - main
    paths:
      - autoinstall-user-data
      - .github/workflows/autoinstall-user-data.yaml  # this workflow

  pull_request:
    branches:
      - master
      - main
    paths:
      - autoinstall-user-data
      - .github/workflows/autoinstall-user-data.yaml  # this workflow

  workflow_dispatch:

permissions:
  contents: read

jobs:
  cloudinit:
    name: Cloud-Init
    uses: HariSekhon/GitHub-Actions/.github/workflows/autoinstall-user-data.yaml@master
