#
#  Author: Hari Sekhon
#  Date: Tue Feb 4 09:53:28 2020 +0000
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/HariSekhon/Templates
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback
#
#  https://www.linkedin.com/in/HariSekhon
#

---
name: Fork Sync

on:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        required: false
        default: false
  schedule:
    - cron: '0 * * * *'

permissions:
  contents: write

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: false

jobs:
  fork_sync:
    if: github.repository_owner != 'HariSekhon'
    name: Fork Sync
    uses: HariSekhon/GitHub-Actions/.github/workflows/fork-sync.yaml@master
    with:
      debug: ${{ github.event.inputs.debug || false }}
