#  vim:ts=2:sts=2:sw=2:et
#
#  Author: Hari Sekhon
#  Date: 2023-05-31 01:49:54 +0100 (Wed, 31 May 2023)
#
#  https://github.com/HariSekhon/Templates
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help steer this or other code I publish
#
#  https://www.linkedin.com/in/HariSekhon
#

---
name: HashiCorp Packer

on:
  push:
    branches:
      - master
      - main
    paths:
      - template.pkr.hcl
      - .github/workflows/packer.yaml  # this workflow

  pull_request:
    branches:
      - master
      - main
    paths:
      - template.pkr.hcl
      - .github/workflows/packer.yaml  # this workflow

  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash -euxo pipefail {0}

jobs:
  packer:
    name: Packer
    timeout-minutes: 10
    runs-on: ubuntu-latest
    container: hashicorp/packer:light
    steps:
      - uses: actions/checkout@v3
        #name: Git Checkout  # better to show the action@version

      - name: Validate template.pkr.hcl
        run: |
          packer init     template.pkr.hcl
          packer validate template.pkr.hcl
