#
#  Author: Hari Sekhon
#  Date: Tue Feb 4 09:53:28 2020 +0000
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/harisekhon/templates
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback
#
#  https://www.linkedin.com/in/harisekhon
#

# ============================================================================ #
#                 S e m g r e p   G i t H u b   W o r k f l o w
# ============================================================================ #

# Generates code scanning alerts in GitHub's Security tab -> Code scanning alerts

# https://semgrep.dev/docs/semgrep-ci/sample-ci-configs/#github-actions

---
name: Semgrep

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  semgrep:
    if: github.event.repository.fork == false
    name: Semgrep GitHub Security Tab
    uses: HariSekhon/GitHub-Actions/.github/workflows/semgrep.yaml@master
    permissions:
      actions: read
      contents: read
      security-events: write
